server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    username: postgres
    password: 3720519635

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update